name: Release Binaries

on:
  push:
    branches:
      - main
    paths:
      - 'linux-amd64/**'
      - 'linux-arm64/**'
      - 'macosx-amd64/**'
      - 'macosx-arm64/**'
      - 'macosx/**'
      - 'windows-amd64/**'
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract version from filenames
        run: |
          VERSION=$(ls linux-amd64 | grep -oP 'v[0-9]+\.[0-9]+\.[0-9]+' | sort -V | tail -1)
          echo "Detected version: $VERSION"
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Create GitHub Release and upload binaries
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: |
            linux-amd64/zksolc-*${{ env.VERSION }}*
            linux-arm64/zksolc-*${{ env.VERSION }}*
            macosx-amd64/zksolc-*${{ env.VERSION }}*
            macosx-arm64/zksolc-*${{ env.VERSION }}*
            macosx/zksolc-*${{ env.VERSION }}*
            windows-amd64/zksolc-*${{ env.VERSION }}*
          tag_name: ${{ env.VERSION }}
          token: ${{ secrets.GITHUB_TOKEN }} 
